### PR TITLE
Minor fix parrots.png to copy on compile as content for editor_example

### PR DESCRIPTION
**Pull request by nikmes**
Minor change in properties of parrots.png to copy on compile.

### CODE REVIEW

**Comment by JeffM2501** [comment]
Thanks for looking at this. I'd much rather not have to copy the resources. If anything I'd like the working directory to be set to where the resources dir is, if that is possible. If not, then I'd rather have the executables copied to the root instead of the resources copied. I'm thinking that if there ends up being more resources, or more samples that share them, we don't want to keep copying them around everywhere, and it's better to just have the samples use the resources in place.

**Review by JeffM2501 — CHANGES_REQUESTED** [review]
I would prefer to not copy the resources. I'd rather set the working dir, or copy the executables.

**Comment by nikmes** [comment]
Cool. I get it but for some reason when I run it in Debug mode from VStudio the texture parrots.png fails to load.

**Comment by nikmes** [comment]
Need to set Workding Directory during Debug to something like C:\Users\nikme\source\repos\rlImGui-cs\editor_example
in order to get them to load.

**Comment by JeffM2501** [comment]
> Need to set Workding Directory during Debug to something like C:\Users\nikme\source\repos\rlImGui-cs\editor_example in order to get them to load.

Yes, I don't use C# daily, but I think there is some way to set the working directory to the solution dir, then it would be good to go with out copying files. Do you know how to do that?

**Comment by JeffM2501** [comment]
I think I have fixed it. I have set the working dir to be the solution dir macro, and moved the resources dir there. Can you test and make sure that works for you as well?

**Pull request closed without merging**
